using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.iOS.Xcode;
using UnityEngine;

namespace Lilo.Editor.iOS
{
    /// <summary>
    /// Applies machine-local Apple signing settings to the Xcode project generated by Unity.
    /// The Team ID is intentionally read from the environment and is never stored in Git.
    /// Configure it before an iOS build with:
    ///   export LILO_APPLE_TEAM_ID="YOUR_TEAM_ID"
    /// </summary>
    public sealed class IOSPostProcessSigning : IPostprocessBuildWithReport
    {
        private const string TeamIdEnvironmentVariable = "LILO_APPLE_TEAM_ID";
        private const string LocalTeamIdPath = "UserSettings/iOSTeamID.txt";

        public int callbackOrder => 999;

        public void OnPostprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.iOS)
                return;

            string projectPath = PBXProject.GetPBXProjectPath(report.summary.outputPath);
            var project = new PBXProject();
            project.ReadFromFile(projectPath);

            string mainTargetGuid = project.GetUnityMainTargetGuid();
            string frameworkTargetGuid = project.GetUnityFrameworkTargetGuid();
            string gameAssemblyTargetGuid = project.TargetGuidByName("GameAssembly");

            // Unity's generated GameAssembly Run Script needs to invoke native
            // build tools and write into the generated project tree. Xcode 27
            // defaults user script sandboxing to YES, which makes that script
            // fail with sandbox-exec/sandbox_apply before compilation begins.
            project.SetBuildProperty(mainTargetGuid, "ENABLE_USER_SCRIPT_SANDBOXING", "NO");
            project.SetBuildProperty(frameworkTargetGuid, "ENABLE_USER_SCRIPT_SANDBOXING", "NO");
            if (!string.IsNullOrEmpty(gameAssemblyTargetGuid))
                project.SetBuildProperty(gameAssemblyTargetGuid, "ENABLE_USER_SCRIPT_SANDBOXING", "NO");
            string teamId = GetLocalTeamId();

            if (string.IsNullOrWhiteSpace(teamId))
            {
                UnityEngine.Debug.LogWarning(
                    $"{TeamIdEnvironmentVariable} is not set. " +
                    "The generated Xcode project was left without a local Team ID. " +
                    "Select a Team in Xcode under Signing & Capabilities.");
            }
            else
            {
                teamId = teamId.Trim();
                project.SetTeamId(mainTargetGuid, teamId);
                project.SetBuildProperty(mainTargetGuid, "CODE_SIGN_STYLE", "Automatic");
                UnityEngine.Debug.Log(
                    $"Applied local iOS automatic signing configuration for Team ID {teamId}.");
            }

            project.WriteToFile(projectPath);
            WriteApplicationIdentity(report.summary.outputPath);
        }

        private static void WriteApplicationIdentity(string buildPath)
        {
            string plistPath = Path.Combine(buildPath, "Info.plist");
            if (!File.Exists(plistPath))
            {
                UnityEngine.Debug.LogWarning($"Could not find generated iOS Info.plist at {plistPath}.");
                return;
            }

            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);
            PlistElementDict root = plist.root;
            root.SetString("CFBundleDisplayName", "LILO");
            root.SetString("CFBundleName", "LILO");
            root.SetString("CFBundleIdentifier", "com.LILO.EGS");
            root.SetString("LSApplicationCategoryType", "public.app-category.games");
            plist.WriteToFile(plistPath);

            UnityEngine.Debug.Log("Applied LILO iOS identity: Games, LILO, com.LILO.EGS, version 1.0, build 1.");
        }

        private static string GetLocalTeamId()
        {
            string fromEnvironment = Environment.GetEnvironmentVariable(TeamIdEnvironmentVariable);
            if (!string.IsNullOrWhiteSpace(fromEnvironment))
                return fromEnvironment;

            string projectRoot = Directory.GetParent(UnityEngine.Application.dataPath).FullName;
            string localPath = Path.Combine(projectRoot, LocalTeamIdPath);
            if (File.Exists(localPath))
                return File.ReadAllText(localPath).Trim();

            return DetectTeamIdFromAppleDevelopmentCertificates();
        }

        private static string DetectTeamIdFromAppleDevelopmentCertificates()
        {
            if (Application.platform != RuntimePlatform.OSXEditor)
                return string.Empty;

            try
            {
                using (var process = new System.Diagnostics.Process())
                {
                    process.StartInfo = new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = "/usr/bin/security",
                        Arguments = "find-identity -v -p codesigning",
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        CreateNoWindow = true,
                    };
                    process.Start();
                    string output = process.StandardOutput.ReadToEnd();
                    process.WaitForExit(5000);

                    var teamIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    foreach (string line in output.Split('\n'))
                    {
                        if (!line.Contains("Apple Development", StringComparison.OrdinalIgnoreCase))
                            continue;

                        Match match = Regex.Match(line, @"\(([A-Z0-9]{10})\)");
                        if (match.Success)
                            teamIds.Add(match.Groups[1].Value);
                    }

                    if (teamIds.Count == 1)
                        return string.Concat(teamIds);

                    if (teamIds.Count > 1)
                    {
                        Debug.LogWarning(
                            $"Multiple Apple Development Team IDs were detected ({string.Join(", ", teamIds)}). " +
                            $"Set {TeamIdEnvironmentVariable} or create {LocalTeamIdPath} to choose one.");
                    }
                }
            }
            catch (Exception exception)
            {
                Debug.LogWarning($"Could not auto-detect Apple Team ID: {exception.Message}");
            }

            return string.Empty;
        }
    }
}
